### PR TITLE
Add wave and breathe mod.

### PR DESCRIPTION
**Pull request by Kwaadpepper**
Fixes https://github.com/wearefractal/msi-keyboard/issues/1
Original PR https://github.com/wearefractal/msi-keyboard/pull/20

Original work by @PaNaVTEC, first adaptation by @tobbebia, first PR adaptation by @ericmarsch

Just made this since @ericmarsch seems inactive.

### CODE REVIEW

**Comment by stevelacy** [comment]
Thanks!

Just a quick change, can you move the arguments for regions from three objects to one?
https://github.com/wearefractal/msi-keyboard/pull/31/files#diff-a6ae09d0821510ff1a6b06e0844a7ac9R3

To be one object:
```js
{
  left: {},
  middle: {},
  right: {}
}
```

That removes the need to check for arguments length, and makes it easier to set just one region.

**Comment by Kwaadpepper** [comment]
I just updated with examples. I believe this is working correctly.

**Comment by Kwaadpepper** [comment]
I don't know why travis fails, but its working here, i don't see any js errors.

**Comment by stevelacy** [comment]
Yep, all actual attempts to send the feature report to the hardware will fail on travis. I'll probably remove (or fake) the tests resolving actually running the hardware.

**Pull request merged**
