### PR TITLE
Ensure device is closed in tests

### PR DESCRIPTION
**Pull request by au-phiware**
Fixes my problem in #12

### CODE REVIEW

**Comment by stevelacy** [comment]
Please move the `require` back to the top of the `main.js` file, it is the node code style.

**Comment by au-phiware** [comment]
Very well, I also needed to reorder the tests to ensure that that particular test ran first...

**Comment by stevelacy** [comment]
Excellent, one more detail: can you remove the .swp files and add them to the git ignore?

**Comment by stevelacy** [comment]
Thanks!

**Pull request merged**
